import Head from 'next/head';
import { ChakraProvider } from '@chakra-ui/react';
import theme from '../theme';

import '../styles/globals.css';

const MyApp = ({ Component, pageProps }) => {
	return (
		<ChakraProvider theme={theme}>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Component {...pageProps} />
		</ChakraProvider>
	);
};

export default MyApp;
